apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-django-config
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.env.DJANGO_SETTINGS_MODULE | quote }}
  DEBUG: {{ .Values.env.DEBUG | quote }}

